"""make email unique

Revision ID: 0205d48b06f1
Revises: cfdf31f1f550
Create Date: 2026-04-08 10:31:15.759806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0205d48b06f1'
down_revision: Union[str, Sequence[str], None] = 'cfdf31f1f550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['email'])
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='unique')
    # ### end Alembic commands ###
