"""add age column

Revision ID: 8165c8a08a4b
Revises: 8532e6dd4ff0
Create Date: 2026-04-06 14:46:53.373247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8165c8a08a4b'
down_revision: Union[str, Sequence[str], None] = '8532e6dd4ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'age')
    # ### end Alembic commands ###
