"""add age column

Revision ID: cfdf31f1f550
Revises: 8165c8a08a4b
Create Date: 2026-04-06 14:57:15.822592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdf31f1f550'
down_revision: Union[str, Sequence[str], None] = '8165c8a08a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('students', 'age',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#     # ### end Alembic commands ###

def upgrade() -> None:
    # 1. Make sure column exists and is nullable
    # (skip if already added in previous migration)

    # 2. Fix NULL values
    op.execute("UPDATE students SET age = 18 WHERE age IS NULL")

    # 3. Now enforce NOT NULL
    op.alter_column(
        'students',
        'age',
        existing_type=sa.INTEGER(),
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
